### ISSUE TITLE
Collaborate

### ISSUE THREAD

**Issue by jilleb** [ibreakifix/PorschePCMStuff#1]
Hello,

I love the work you've done! I have some stuff I would like to discuss with you. Is there any way we can connect outside of Github?

**Comment by ibreakifix** [comment]
Of course, I don't want to post my email publicly, so I made a private repo with my contact info and sent you an invite

**Comment by xerqus** [comment]
Hello 
can you send me your contact info pls ? i am doing some modification on Porsche cars and really can use your help
